[package]
name = "gmix"
version = "1.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.51"
derive_more = "0.99.17"
futures = "0.3.18"
glib = "0.14.8"
gstreamer = "0.17.4"
